# apiVersion: v1
# kind: Service
# metadata:
#   name: order
#   labels:
#     app: order
# spec:
#   ports:
#     - port: 8080
#       targetPort: 8080
#   selector:
#     app: order
#     type: "ClusterIP"
apiVersion: v1
kind: Service
metadata:
  name: store-backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/actuator"
spec:
  selector:
    app: store-backend
  type: NodePort
  ports:
    - port: 8080 # 서비스가 생성할 포트
      targetPort: 8080 # 서비스가 접근할 pod의 포트
      protocol: TCP
